name: "PHPUnit Tests"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  phpunit:

    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "7.4"
          - "8.0"
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: ${{ matrix.php-version }}
          ini-values: "memory_limit=-1"

      - name: "Get Composer cache directory"
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: "Cache Composer packages"
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}-${{ matrix.dependencies }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: "Install lowest dependencies"
        if: ${{ matrix.dependencies == 'lowest' }}
        run: "composer update --prefer-lowest --no-interaction --no-progress --no-suggest"

      - name: "Install highest dependencies"
        if: ${{ matrix.dependencies == 'highest' }}
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: "Tests"
        run: "vendor/bin/phpunit --coverage-clover=clover.xml --coverage-text"

      - name: "Coverage processing"
        if: ${{ github.ref == 'refs/heads/master' && matrix.dependencies == 'highest' &&  matrix.php-version == '8.0' }}
        uses: steffendietz/clover-to-shieldsio-json-action@v1.0
        with:
          path-to-clover: "clover.xml"
          path-to-json: "build/shieldsio-coverage.json"
          style: "flat-square"

      - name: "Deploy coverage"
        if: ${{ github.ref == 'refs/heads/master' && matrix.dependencies == 'highest' &&  matrix.php-version == '8.0' }}
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: build